### ISSUE TITLE
add option to write output  to file (default is stdout)

### ISSUE THREAD

**Issue by rafaelfolco** [perftool-incubator/multiplex#35]
include --output arg (default = bench-params.json)

**Comment by k-rister** [comment]
I like the idea of adding `--output`, but I wonder if the default case should still be to print the output to STDOUT instead of a specific file.  I don't like the idea of somebody accidentally overwriting an existing `bench-params.json` file just because they didn't provide an argument.

**Comment by rafaelfolco** [comment]
> I like the idea of adding `--output`, but I wonder if the default case should still be to print the output to STDOUT instead of a specific file. I don't like the idea of somebody accidentally overwriting an existing `bench-params.json` file just because they didn't provide an argument.

Fair point. We can make it  stdout by default, but we need to change the code to raise exceptions and errors to stderr instead.

**Comment by k-rister** [comment]
> Fair point. We can make it stdout by default, but we need to change the code to raise exceptions and errors to stderr instead.

Agreed.
